import Navbar from "@/components/NavBar/Navbar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-890 text-slate-300">
        <Navbar />
        <div className="ml-72">{children}</div>
      </body>
    </html>
  );
}
